language: c
compiler:
  - clang
script:
  - clang src/main.c -o lst -g
  - ./lst

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    # macOS
    - os: osx

    # Linux, various Ubuntu Versions
    # (16.04 Xenial, 18.04 Bionic, 20.04 Focal)

    # AMD
    - os: linux
      dist: focal
      arch: amd64

    - os: linux
      dist: bionic
      arch: amd64

    - os: linux
      dist: xenial
      arch: amd64

    # ARM
    - os: linux
      dist: focal
      arch: arm64

    - os: linux
      dist: bionic
      arch: arm64

    - os: linux
      dist: xenial
      arch: arm64
